### ISSUE TITLE
Error with tabulating cross correlation functions. 

### ISSUE THREAD

**Issue by Mert-Okyay** [johannesulf/TabCorr#1]
Hello, 

I was attempting to tabulate cross correlations between the bolplanck simulation and some other catalogue. This is the error:

  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tabcorr\tabcorr.py", line 328, in tabulate
    (len(xi.ravel()), len(halotab.gal_type)))
AttributeError: 'tuple' object has no attribute 'ravel'

I believe this issue is because in the *tcpf arguments, I provided a second sample which corresponds to sample2 in the arguments of halotools wp, which then causes three np arrays to be returned in a tuple, which does not accept the ravel or shape methods. 

By changing xi to xi[1] (the ccf component) in line 314 elif mode='cross', I got it to work for now(still running) but I am not sure if this will mess other things up.

I would appreciate a look, thanks.

**Comment by johannesulf** [comment]
Sure! What you're saying sounds right. I wouldn't consider the behavior by TabCorr a bug. But I should update the docstring to make clear that the `tpcf` argument passed to the `tabulate` should return a single array. Maybe I can also add an appropriate error message.`halotools.mock_observables.wp` has the `do_auto` keyword argument that, I believe, you can set to `False` such that `wp` will only return the cross-wp and you don't have to change any code in `TabCorr`.

I take that you're interested in calculating the cross-wp between some tracer sample defined by an HOD and a second sample. Is the second sample assumed to be fixed, i.e. doesn't have an HOD? I want to make sure I understand the use case.

**Comment by Mert-Okyay** [comment]
Thanks for the swift reply!

What you've said is right, what I was trying to do is tabulate cross correlation functions between the simulation and some real galaxy sample (LRGs from BOSS), so that I could use this to fit an HOD model with MCMC to a different galaxy sample(peas) that I am interested in, by comparing the LRG-pea cross correlation to the HOD-LRG CCF. 

I wasn't aware that the do_auto would prevent the issue, it makes sense though. 

If you wouldn't mind, I have other questions on how to use this for MCMC. Could I reach you by e-mail on this?

**Comment by johannesulf** [comment]
Sure! You can find my email on my website: https://johannesulf.github.io/.
