### ISSUE TITLE
Questions on passing Assembly Bias parameters into Tabcorr.

### ISSUE THREAD

**Issue by Sherlockids** [johannesulf/TabCorr#5]
- I used a decorated HOD model and set the `'halo_nfw_conc'` as the `'sec_haloprop_key'`: 

```
AB_para = [11.973, 0.298, 0.928, 13.118, 12.420, 1, 1]

model   = PrebuiltHodModelFactory('zheng07', threshold = -20)# threshold for Mr 
#########################################################################################
new_cen_occ_model = PreservingNgalAssembiasZheng07Cens(assembias_strength = AB_para[5], prim_haloprop_key='halo_mvir', sec_haloprop_key='halo_nfw_conc')
new_sat_occ_model = PreservingNgalAssembiasZheng07Sats(assembias_strength = AB_para[6], prim_haloprop_key='halo_mvir', sec_haloprop_key='halo_nfw_conc')

AB_model     = HodModelFactory(baseline_model_instance = model, 
                                    centrals_occupation     = new_cen_occ_model,
                                    satellites_occupation   = new_sat_occ_model)
AB_model.param_dict['logMmin']    = AB_para[0]
AB_model.param_dict['sigma_logM'] = AB_para[1]
AB_model.param_dict['alpha']      = AB_para[2]
AB_model.param_dict['logM1']      = AB_para[3]
AB_model.param_dict['logM0']      = AB_para[4]

halocat = CachedHaloCatalog(simname='SMDPL', redshift=0.0, halo_finder='rockstar', version_name = 'rockstar') 
AB_model.populate_mock(halocat)
```

- Then I compare the `wp(rp)` results between `Tabcorr`and `Halotools` when `Aces = Asat = 1`, but found they are different from each other(they match when Assembly Bias = 0).

wp in Tabcorr way
```
rp_bins = np.logspace(-0.8, 1.6, 13)

halocat = CachedHaloCatalog(simname = 'SMDPL', halo_finder = 'rockstar', version_name = 'rockstar', redshift = 0.0) # 400 Mpc/h

from astropy.cosmology import Planck13
halocat.cosmology = Planck13

halotab = TabCorr.tabulate(halocat, wp, rp_bins, pi_max=40., verbose=True, num_threads=100, sec_haloprop_key='halo_nfw_conc')

halotab.write('smdpl_wp_pimax40.hdf5')

halotab   = TabCorr.read('smdpl_wp_pimax40.hdf5')
AB1_ngal_tabcorr, AB1_wp_tabcorr = halotab.predict(AB_model)
```
wp in Halotools way:
```
galaxies = AB_model.mock.galaxy_table
x = galaxies["x"]
y = galaxies["y"]
z = galaxies["z"]
vz= galaxies["vz"]
period = AB_model.mock.Lbox

cosmo = cosmology.Planck13

xyz = return_xyz_formatted_array(x, y, z, velocity=vz, velocity_distortion_dimension="z", period=halocat.Lbox, cosmology=cosmo)
AB1_ng_halotools = len(x)/(period[0]**3) # (Mpc/h)^3
AB1_wp_halotools = wp(xyz, rp_bins = rp_bins, pi_max = pi_max, period=period, num_threads='max')
```

![image](https://github.com/user-attachments/assets/483e2ce5-1f12-4cea-8540-7cdd7dc50712)

**Comment by johannesulf** [comment]
Hi @Sherlockids, thanks for reaching out. My suspicion is that this is related to the `PreservingNgalAssembiasZheng07Sats` class. Does the same happen with `AssembiasZheng07Sats`?

**Comment by Sherlockids** [comment]
It's the same with `AssembiasZheng07Cens/Sats` or `PreservingNgalAssembiasZheng07Cens/Sats`:
![image](https://github.com/user-attachments/assets/cae923e5-d26a-4bb1-a2d2-396e57dec282)
And we have checked the HOD of `PreservingNgalAssembiasZheng07Cens/Sats` model, which seems all right (the right column decribes the differences between `Assembly Bias = 1` and `Assembly Bias = 0`):
![image](https://github.com/user-attachments/assets/94caf063-9515-4857-bfdd-b0afcc184a7e)
Also, we applied `PreservingNgalAssembiasZheng07Cens/Sats` in `Galtab` for `PNcic`, where this problem didn't occur:
![image](https://github.com/user-attachments/assets/037e32d8-173d-418e-8473-88d5713f4068)

**Comment by johannesulf** [comment]
@Sherlockids Can you send me the TabCorr file via email to jlange@american.edu? Thanks!

**Comment by Sherlockids** [comment]
By adding the ` "sec_haloprop_percentile_bins=0.5” `while tabulating, the results of Tabcorr now align with the halo tools, thanks again for your help.
`halotab = TabCorr.tabulate(halocat, wp, rp_bins, pi_max=40., verbose=True, num_threads=150, sec_haloprop_key='halo_nfw_conc', sec_haloprop_percentile_bins = 0.5)
`
![image](https://github.com/user-attachments/assets/67fb9c96-2122-40b7-a1e9-c7874c421822)
